
export enum ManageUserOperations  {
    GET_USERS = "GET_USERS",
    USERS_ERROR = "USERS_ERROR",
    USERS_FETCHING = "USERS_FETCHING",
    RESERVATION_CHANGE_STATUS_ADM = "RESERVATION_CHANGE_STATUS_ADM"
}