
export enum ReservationOperationTypes {
    RESERVATION_IS_FETCHING = "RESERVATION_IS_FETCHING",
    RESERVATION_FETCH = "RESERVATION_FETCH",
    RESERVATION_FETCH_ERROR = "RESERVATION_FETCH_ERROR",

    ACCOMMODATION_DELETE = "ACCOMMODATION_DELETE",
    ACCOMMODATION_DELETE_FETCHING = "ACCOMMODATION_DELETE_FETCHING",
}